name: Run unit tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install --include-dev
      - name: Run Tests
        run: |
          npm run test
